svetlanouchka/wavely-app

backend/package-lock.json
backend/package.json
backend/src/Middlewares/validateUser.js
backend/src/router.js

Middleware for validate User (signup) with express-validator.
Fields first_name, last_name, birth_date, email, hached_password with constraints and error messages.
NB : the http request contain "hached_password" but we had to change this when implement hashPassword middleware (client send a data "password" and not "hached_password").

validate user with express-validator

---

frontend/src/BackgroundAnimation.css
frontend/src/components/BackgroundCanvas.jsx
frontend/src/pages/HomePage.jsx

Animation with keyframes and cubic bezier and repeating-radial-gradient
Responsive
40s infinite loop

responsive animated background with infinite loop

---

backend/package-lock.json
backend/src/controllers/sessionControllers.js
backend/src/models/SessionManager.js
backend/src/models/index.js
backend/src/router.js

Routes session (séance)
GET - Read all and Find by id
ADD - Post a session
UPDATE - Edit a comment (feeling post-session)

routes session (séance) read - add - update

---

backend/src/controllers/tagControllers.js
backend/src/models/TagManager.js
backend/src/models/index.js
backend/src/router.js

Nouvelle route back implémentée
GET - Browse pour récupérer tous les tags
GET - Read pour récupérer un tag par son id
PS: j'ai modifié la table tag car pour le champ 'nom' il y avait écrit 'tag' ce qui portait à confusion

route tag browse - find by id

---

frontend/src/Router.jsx
frontend/src/components/Layout/Layout.jsx

I moved the component HomePage out of AppLayout in react router pour séparer la page d'accueil du reste de l'app et afficher l'animation

Pb animation

---

frontend/src/components/Frequency.jsx
frontend/src/ui/ButtonMain.jsx

added button main

---

frontend/src/components/Category.jsx
frontend/src/components/Frequency.jsx

added composant category and filter function

added category

---

frontend/src/Router.jsx
frontend/src/components/Frequency.jsx
frontend/src/pages/FrequenciesPage.jsx
frontend/src/pages/FrequencyPage.jsx
frontend/src/ui/ButtonMain.jsx

Added a page for frequency detailed view
Newt step recommended frequencies and tag

page unique frequency

---

frontend/src/App.css
frontend/src/components/Layout/Footer.jsx
frontend/src/components/Layout/Header.jsx
frontend/src/components/Layout/Layout.jsx
frontend/src/components/LogoW.jsx
frontend/src/pages/HomePage.jsx
frontend/src/ui/ButtonLaunch.jsx

Dynamic header
New file logo W for découpage des composants
Beautiful homepage with animation

Dynamic header | new file logo W | homepage with animation

---

frontend/src/App.css
frontend/src/components/CrossIcon.jsx
frontend/src/components/Layout/Header.jsx
frontend/src/components/Layout/Layout.jsx
frontend/src/components/LogoW.jsx
frontend/src/components/NavDesktop.jsx
frontend/src/components/NavMobile.jsx

Logo on header homepage mobile but not desktop
Logo on header layout mobile and desktop
Header layout responsive and centré
New calcul layout for caler le footer en bas de la page

logo and header

---

frontend/src/Router.jsx
frontend/src/components/Layout/Header.jsx
frontend/src/components/NavDesktop.jsx
frontend/src/components/NavMobile.jsx
frontend/src/pages/LoginPage.jsx
frontend/src/ui/ButtonLaunch.jsx

Button intégré mais pas réussi à faire l'effet blur. Je dirais au stagiaire de s'en occuper.

launch ok but not blur

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/BackgroundShapes.jsx
frontend/src/components/Layout/Footer.jsx
frontend/src/components/SignUpForm.jsx
frontend/src/pages/ContactPage.jsx
frontend/src/pages/SignupPage.jsx
package-lock.json
package.json

Added BackgroundShapes component 
and moved yup and formik to frontend

added background shapes

---

backend/package-lock.json
backend/package.json
backend/src/Middlewares/validateUser.js
backend/src/controllers/userControllers.js
backend/src/models/UserManager.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/SignUpForm.jsx

Débug réussi --> formatage de la bonne date dans le front et avant l'envoi à la bdd
Suppression du champ confirmPassword avant envoie au middleware userValidate
Installation du module date-fns dans front et back

signup works

---

backend/src/Middlewares/validateUser.js
backend/src/controllers/userControllers.js
frontend/src/components/SignUpForm.jsx

J'ai enlevé les logs inutiles et ajouté un envoi de status 201 (created) dans le add controller

remove useless logs and add 201 status in add controller

---

backend/src/controllers/categoryControllers.js
backend/src/controllers/frequencyControllers.js
backend/src/controllers/frequencytagControllers.js
backend/src/models/FrequencyTagManager.js
backend/src/models/index.js
backend/src/router.js
frontend/index.html
frontend/src/components/Category.jsx
frontend/src/components/Tag.jsx
frontend/src/pages/FrequencyPage.jsx
frontend/src/ui/ButtonMain.jsx

Added category visualisation to the FrequencyPage
Added tag visualisation to the FrequencyPage

added categories and tags to Frequency Page

---

frontend/index.html
frontend/package.json
frontend/src/tests/formatDate.js
frontend/src/tests/formatDate.test.js
package-lock.json
package.json

Added jest
Made an attempt to complete a test unitaire
problem of import vs require
to resolve soon

test unitaire

---

frontend/src/App.css
frontend/src/assets/Arrow-left.svg
frontend/src/assets/Arrow-right.svg
frontend/src/components/Modals/StepIntroduction.jsx
frontend/src/components/Modals/StepPreferences.jsx
frontend/src/components/Modals/StepStressEvaluation.jsx
frontend/src/hooks/useSessionFlow.jsx
frontend/src/pages/FrequencyPage.jsx
frontend/src/ui/Modal.jsx
frontend/src/ui/NextStepButton.jsx
frontend/src/ui/PrevStepButton.jsx

Added a personnalised hook useSessionFlow that uses Reducer
Added Modal composant and composants for 3 steps

modal before

---

backend/package-lock.json
backend/package.json
backend/src/controllers/contactControllers.js
backend/src/router.js
backend/src/utils/sendEmail.js

Route back to send an email with NodeMailer
J'ai utilisé Ethereal pour générer une fausse boite mail
Route fonctionnelle en back

route back contact with nodemailer and ethereal

---

backend/src/utils/sendEmail.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/ContactForm.jsx
frontend/src/components/NavMobile.jsx

Send a message from contact from
Notification (react-toastify) quand c'est envoyé
Formatage des messages (retours à la ligne pris en compte)

Post a message from frontend with little notification success

---

compteBancaire.js
frontend/src/components/Modals/StepPostSession.jsx
frontend/src/components/Modals/StepPreferences.jsx
frontend/src/components/Modals/StepStressEvaluation.jsx
frontend/src/ui/FieldComment.jsx
frontend/src/ui/Modal.jsx
frontend/src/ui/StarReview.jsx
package-lock.json
package.json

Modal StepPostSession
had to add NextStepButton just to visualise - need to change it after 
added react-icons library

modal_after

---

frontend/src/components/Modals/StepIntroduction.jsx
frontend/src/components/Modals/StepPostSession.jsx
frontend/src/components/Modals/StepPreferences.jsx
frontend/src/components/Seance.jsx
frontend/src/hooks/useSessionFlow.jsx
frontend/src/pages/FrequencyPage.jsx
frontend/src/ui/Modal.jsx

Added initialStep so that from Seance user opens modal step 4

step4 opens from seance

---

backend/src/controllers/sessionControllers.js
frontend/src/components/Modals/StepPostSession.jsx
frontend/src/components/Modals/StepPreferences.jsx
frontend/src/components/Modals/StepStressEvaluation.jsx
frontend/src/components/Seance.jsx
frontend/src/hooks/useSessionFlow.jsx
frontend/src/pages/FrequencyPage.jsx
frontend/src/pages/LoginPage.jsx
frontend/src/ui/FieldComment.jsx
frontend/src/ui/Modal.jsx
frontend/src/ui/StarReview.jsx

Paramètres des modals pour configurer la séance
POST informations de séance dans la BDD
Suppression du container blanc
Correction du bug note before
Correction du bug review
Correction du bug comment
Correction des bugs de fetch des audios (chemins erronés)

session works

---

frontend/src/components/Layout/Layout.jsx
frontend/src/pages/AboutPage.jsx

Page about
Mise en page des textes, titres, images
Intégration vidéo waves
Avatars
Cards for frequency shapes
Warning in red
Button link to frequencies
Modification du layout (suppression du padding de main)

page about ok

---

frontend/src/pages/AboutPage.jsx

Video touch edges with success

video touch edges

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.css
frontend/src/components/AffirmationScreen.jsx
frontend/src/components/Seance.jsx

Text animation scroll with wonderful scrollbar

beautiful scroll text affirmation

---

frontend/src/components/AffirmationScreen.jsx
frontend/src/components/Seance.jsx

text scroll ok

---

frontend/src/Router.jsx
frontend/src/components/Layout/Footer.jsx
frontend/src/components/Layout/Layout.jsx
frontend/src/components/Rectangle.jsx
frontend/src/pages/UserPage.jsx

Page Mon Espace but not finish because we need le back

espace user front (not finish)

---

backend/src/models/SessionManager.js
frontend/src/components/ModalSession.jsx
frontend/src/components/Rectangle.jsx
frontend/src/pages/UserPage.jsx

Fetch data session and frequency in a modal
Bouton close modal
Added non-breakable spaces

modal stats session for a user

---

backend/src/controllers/frequencyControllers.js
frontend/src/Router.jsx
frontend/src/pages/FrequencyPage.jsx
frontend/src/pages/Status404.jsx

Page de statut 404 pour URL invalide
Id transformé en number dans frequencypage pour éviter les erreur d'URL

404 NOT FOUND

---

frontend/src/components/Layout/Header.jsx
frontend/src/components/SignUpForm.jsx
frontend/src/pages/ContactPage.jsx
frontend/src/pages/FaqPage.jsx
frontend/src/pages/FrequenciesPage.jsx
frontend/src/pages/LoginPage.jsx
frontend/src/pages/MyProfilePage.jsx
frontend/src/pages/SignupPage.jsx
frontend/src/ui/LogoutButton.jsx
frontend/src/ui/Modal.jsx

CSS improvements
Ajout du modal de confirmation après la séance 
Ajout du bouton "Mon Espace"

css improvements and bugs

---

frontend/src/components/LoginForm.jsx
frontend/src/pages/FrequencyPage.jsx
frontend/src/ui/ButtonMain.jsx

- Redirige vers le login form si user non connecté veut lancer une séance

navigate to login if no connected to launch a session

---

frontend/index.html
frontend/src/components/Category.jsx
frontend/src/components/ContactForm.jsx
frontend/src/components/Frequency.jsx
frontend/src/components/LoginForm.jsx
frontend/src/components/ModalSession.jsx
frontend/src/components/Modals/ModifyProfil.jsx
frontend/src/components/Seance.jsx
frontend/src/components/SignUpForm.jsx
frontend/src/components/Tag.jsx
frontend/src/pages/FrequencyPage.jsx
frontend/src/pages/MyProfilePage.jsx
frontend/src/pages/UserPage.jsx
frontend/src/ui/Modal.jsx

Replaced all localhost by import.meta.process.env
And url for favicon in index.html

replaced all localhost by import.meta.process.env

---

backend/src/app.js
frontend/src/components/Layout/Layout.jsx
frontend/src/components/NavDesktop.jsx
frontend/src/components/NavMobile.jsx
frontend/src/pages/MyProfilePage.jsx
frontend/src/pages/UserPage.jsx
frontend/src/ui/ButtonLaunch.jsx

Refacto css : 
- Centrage du bouton launch
- Bouton Profil apparait en mobile quand connecté
- Recalcul du main dans layout
- Agrandissement du conteneur MyProfil

css improvements

---

frontend/src/components/Layout/Footer.jsx
frontend/src/components/NavMobile.jsx

J'ai foncé la background-color du footer ppur plus de constraste
J'ai aussi ajouté un gap entre les éléments

new footer color and gap on elements

---

frontend/src/components/SignUpForm.jsx

If signup works --> navigate to login form

navigate to login after signup
